export type ItemsBillsToReceiveData = {
  ID_PSS: string;
  ID_SDS: string;
  ID_RCB: string;
  ID_ORIGEM: string;
  DATA_LANCAMENTO: string;
  DATA_VENCIMENTO_RCB: string;
  DATAHORA_PAGAMENTO_RCB: string;
  DATA_RECEBIMENTO_RCI: string;
  VALOR_RCB: string;
  RESTANTE_RCB: string;
  JUROS_RCB: string;
  MULTA_RCB: string;
  VALOR_PAGO_RCB: string;
  APELIDO_PSS: string;
  VENDEDOR: string;
  FORMA_PAGAMENTO: string;
  STATUS_RCB: string;
  ATRASO_RCB: string;
  MES_ANO: string;
  PORCENTAGEM: string;
};
